### ISSUE TITLE
Ideas around logging and frameworks

### ISSUE THREAD

**Issue by reesemclean** [skreutzberger/SwiftyBeaver#18]
Our application is split into quite a few frameworks. Our ideal logging solution would be something that allows us to change logging verbosity per framework (using CocoaPods). With a global variable in the AppDelegate I don't see how the frameworks could access it or have logging at all?

This is possible with CocoaLumberjack and Objective-C but it requires using macros. I'm not sure how or if this sort of logging can happen with the approach. Any ideas on this?

**Comment by skreutzberger** [comment]
Would these frameworks be identifiable with source code filename or folder? I anyway wanted to add whitelisting based on files which means having different logging verbosity per file(s)/folder(s) in a very simple way.

**Comment by reesemclean** [comment]
I'm sure they could be identified via their module? I will look into that more and get back to you.

The bigger issue is how they even get access to the `log` global variable to send messages in the first place? That's what I'm wondering; does this approach work with frameworks?

**Comment by skreutzberger** [comment]
Theoretically you should be able to reference the log (SwiftyBeaver.self) variable in the main app from a public log (or whatever name) variable which exists in the frameworks. The framework should then "know" about the variable. But I could be wrong because it does not know the underlying logging framework.

The safest would be to let all your frameworks use SwiftyLogger and then the variable referencing should work.

**Comment by reesemclean** [comment]
Oh right. For some reason I read it the first time as initializing a new log variable rather than assigning it a shared one. This should work fine as we would use it across all our frameworks. Thanks!

I will close this and add a comment to the previous issue on per file logging about per module logging.
