### ISSUE TITLE
File-based logging levels

### ISSUE THREAD

**Issue by adonoho** [skreutzberger/SwiftyBeaver#2]
Gentlefolk,

In Objective-C, I could build a simple macro around NSLog that allowed me to turn logging on/off on a per file basis. This allowed me to keep logging rich source code base while turning off logging for most of my project. This dramatically reduced the noise in my logs while I'm building and debugging features. 

Can SwiftyBeaver be made to do this?

Anon,
Andrew

**Comment by skreutzberger** [comment]
Hi Andrew,

that's a great idea and use case that would really make sense. SwiftyBeaver’s log functions (log.debug(), log.info(), etc.) are getting the filename (and more) as parameter so a filter would be possible there. 

How did you do your filter / toggle? A list of filenames in a whitelist / blacklist or something more magic?

Best,

Sebastian

**Comment by adonoho** [comment]
Sebastian,

At the top of each file in which I want to control logging, I had the following:

```
//#define CLASS_DEBUG 1
#import "DDGMacros.h"
```

If I wanted log entries from a file. I uncommented the `#define CLASS_DEBUG`. Here is an example macro that utilized the `CLASS_DEBUG`:

```
//
// DDGLog() is a parameter identical substitute for NSLog() which also 
//   logs the function name and line number.
// void DDGLog(NSString *format, ...);
//

void _DDGLog(const char *name, int line, NSString *format, ...);
#if (defined DEBUG && defined CLASS_DEBUG)
#define DDGLog(format, ...) (_DDGLog(__PRETTY_FUNCTION__, __LINE__, (format), ##__VA_ARGS__))
#else
#define DDGLog(format, ...)
#endif
```

How you would do this with SwiftyBeaver is up to you. I suspect editing a file of active methods would be workable. 

Allow me to emphasize something. The simplicity of SwiftyBeaver is very attractive. I teach beginning iOS programming at my local community college. Your competitor, `XCGLogger`, has multiple problems being easily used in my student's projects. Any mechanism you choose, please ensure that your logger stay easy to implement. My logging macros are all I ever really needed in my Objective-C apps. In Swift, I need something equally simple. Log levels are overkill and per file logging is much more important.

Keep up the good work.

Anon,
Andrew

**Comment by skreutzberger** [comment]
Andrew,

thank you so much for your kind words and it is wonderful that you teach
iOS at your local community college!

Simplicity is the key in software design and at all the companies I was
working in the past as CTO or CEO that was my #2 goal in product
development (#1 was user-focus but that also relates to goal #2).

But back to your idea: since Swift does not have header files and the
direct interaction with each file would cause issues if you work in a team
environment I would maybe do a solution with a simple blacklist and/or
whitelist array.

Every developer can than have that array in his own not-source-controlled
config and can write and debug code without harming the logging of his team
mates.

If I have time I will write a solution later this week and will then reply
to your issue so that other people can contribute their ideas, too.

Be sure, my solution will be simple and will not blow up the code :)

Before I end, 2 shameless self-promotional things which still may come
handy for you or your students, too:

1. Every new developer I did hire in the past (I interviewed surely more
than 200 in my life) I just told one golden rule:

"Avoid coding at all. Start thinking first! Every line of code makes your
software more buggy and after a bit of thinking you always come up with a
simpler, more elegant and more reduced version of your idea."

2. Since you teach iOS you may also find my recent article about How to
build an iOS app without signup screen interesting. I am not a good writer
and I am even not natively English-speaking but I already got more than 280
Likes on Medium (which is a lot for a tech-based article) and a very
positive response from some thought leaders in UX design and iOS
development.

Here is the link:
https://medium.com/welcome-aboard/ios-onboarding-without-signup-screens-cb7a76d01d6e#.6zy2o52fv

Andrew, just tell me if I can do more for you and if possible please also
openly communicate in Github Issues. It is my first "real" open source
project (before that I "just" lead an open source-based startup, hehe and
did closed-sourced stuff) and I am very happy on the already very positive
Swift community feedback.

Best regards,

Sebastian


2015-12-01 17:43 GMT+01:00 Andrew W. Donoho <notifications@github.com>:

**Comment by reesemclean** [comment]
For module level logging I don't see a good way to specify a module. Ideally just like a file whitelist/blacklist you could have a module whitelist/blacklist.

You can get the equivalent if your module is in another folder and whitelist that folder? It's not as clean as just whitelisting a module name but it would work.

Just for a reference, here is the folder structure for our frameworks using CocoaPods:

`.../PROJECT_NAME/Pods/POD_NAME/Pod/Classes/../FILE_NAME.swift`

So for the whitelist the user would specify something like:

`../Pods/POD1/*`

Which would turn on logging for the whole module (technically all the files in that folder)?
