### ISSUE TITLE
Clickable filenames in logs

### ISSUE THREAD

**Issue by samsonjs** [skreutzberger/SwiftyBeaver#22]
@krzysztofzablocki has a new Xcode plugin for clickable filenames in logs [krzysztofzablocki/KZLinkedConsole](https://github.com/krzysztofzablocki/KZLinkedConsole), and AppCode has that feature too. They use the format `filename:line` so it would be cool to collaborate and have a default format that has clickable links for those using them.

**Comment by skreutzberger** [comment]
Interesting plugin and timesaver! SwiftyBeaver uses a more readable output format which removes the .swift (because anyway every file is .swift) and adds the function name and then the line in the format

`FilenameWithoutSuffix.FunctionName():Line`

@krzysztofzablocki - is there any way for you to support that format?

**Comment by krzysztofzablocki** [comment]
hey, if someone can write a regex that works for both then no problem at all :) not that good at regular expressions. Ideas how to make it additive?

I do not want to disable old format because not only do a lot of projects have differen types of files but also because the plugin supports being able to click on `MyDataThatGeneratedError.json:20`

**Comment by skreutzberger** [comment]
Yeah, regex are really a pain and I always need to look it up again.
What about additionally supporting SwiftyBeaver's format?

**Comment by krzysztofzablocki** [comment]
Knowing @samsonjs I bet he can write a regex that's additive, if not we'll add it other way so you can use it for SwiftyBeaver

**Comment by skreutzberger** [comment]
That would be fantastic! Can’t wait until you tell me that it’s ready. Oh one more wish ;)

Would it be okay if either SwiftyBeaver’s repo or your repo holds a prebuilt version of the extension? That would make installation for the user so much simpler. I did the same for Xcode Colors and it works like a charm.

**Comment by krzysztofzablocki** [comment]
Yeah you can add my plugin pre-built, just don't forget attribution info :)

**Comment by skreutzberger** [comment]
Absolutely! Just ping me when the new plugin is ready. I can’t wait to see it in action.

**Comment by samsonjs** [comment]
Sure I can take a look at that, shouldn't be too much trouble to make it work with multiple formats.

**Comment by skreutzberger** [comment]
Thank you! I am working now on the integration and will host the built plugin in the Asset folder.

**Comment by skreutzberger** [comment]
@krzysztofzablocki Maybe you can mention SwiftyBeaver as supporting (and preferred?) logger for your plugin in your Readme or so?

 KZLinkedConsole & SwiftyBeaver teaming-up :)

http://i.giphy.com/E4EhibkxIt7YA.gif

**Comment by krzysztofzablocki** [comment]
It's already mentioned there, I asked @samsonjs to add it and he did before we merged

**Comment by skreutzberger** [comment]
ah, perfect, thanks!
